name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno environment
        uses: denolib/setup-deno@master
      - name: Show Deno version
        run: deno --version
      - name: Run lint
        run: deno fmt --check */**.ts
      - name: Run tests
        run: deno test -A --unstable tests/*.ts
